### ISSUE TITLE
Deprecation Notice: Creation of dynamic property

### ISSUE THREAD

**Issue by worldwidehigh** [eibiflo/cf_cookiemanager#52] opened 2024-11-22 13:56 UTC
In TYPO3 v12.4.23, PHP v8.2.24 I get this error message in the backend:

`PHP Runtime Deprecation Notice: Creation of dynamic property CodingFreaks\CfCookiemanager\Domain\Model\Scans::$unknownProvider is deprecated in /home/www/drk-webseite-v2/vendor/codingfreaks/cf-cookiemanager/Classes/Domain/Repository/ScansRepository.php line 131`

**Comment by eibiflo** [comment] 2024-11-23 07:13
Thanks for the issue, will be fixed in the next public release.

**Closed by eibiflo** 2024-11-23 07:13 UTC

**Comment by worldwidehigh** [comment] 2024-11-23 07:28
Thank you for your quick reply. I have downloaded the new files and changed it in my version, now a new error occurs:

```
(1/1) TypeError
CodingFreaks\CfCookiemanager\Domain\Model\Scans::setUnknownprovider(): Argument #1 ($unknownprovider) must be of type array, int given, called in /home/www/drk-webseite-v2/vendor/codingfreaks/cf-cookiemanager/Classes/Domain/Repository/ScansRepository.php on line 131

in /home/www/drk-webseite-v2/vendor/codingfreaks/cf-cookiemanager/Classes/Domain/Model/Scans.php line 211
     *
     * @param array $unknownprovider
     * @return void
     */
    public function setUnknownprovider(array $unknownprovider)
    {
        $this-&gt;unknownprovider = $unknownprovider;
    }

at CodingFreaks\CfCookiemanager\Domain\Model\Scans-&gt;setUnknownprovider(0)
in /home/www/drk-webseite-v2/vendor/codingfreaks/cf-cookiemanager/Classes/Domain/Repository/ScansRepository.php line 131
            if(!empty($provider)){
                $foundProvider = count($provider);
            }
            $scan-&gt;setFoundProvider($foundProvider);
            $scan-&gt;setUnknownProvider($unknownProvider);
            $preparedScans[] = $scan-&gt;_getProperties();
        }
        return $preparedScans;
    }
```

**Comment by eibiflo** [comment] 2024-11-23 07:49
Thank you!
I overlooked the edge case, this happens when no unknown providers are found during the scan.

**Comment by eibiflo** [comment] 2024-11-23 09:16
The problem is that the logic is not perfectly implemented, sorry for this.
The scan and import logic will be refactored soon once I finish the new scanner api, so it can be handled more cleanly.

For now, I would simply treat the variable as mixed. It's not ideal, but it still works with the Autoconfig Logic.
